11-01 09:15 - [INFO] (export.py).<module>(15) - Формируем:Pharmit
11-01 09:15 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./export/pharmit/
11-01 09:15 - [INFO] (system.py).clear_export_path(52) - Удаленно 0 файлов
11-01 09:15 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./log/
11-01 09:15 - [INFO] (system.py).clear_export_path(52) - Удаленно 5 файлов
11-01 09:15 - [INFO] (engine.py).wrapper(33) - Выполняю: create, 'file'
11-01 09:15 - [INFO] (engine.py).create(172) - .\export\file
11-01 09:15 - [INFO] (engine.py).create(185) - Загружаю алгоритм выгрузки:Pharmit
11-01 09:15 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 09:15 - [INFO] (pharmit.py).send_request(43) - https://api.pharmit.kz/api/loadhistories-200- OK-
229177
11-01 09:15 - [INFO] (pharmit.py).send_request(43) - https://api.pharmit.kz/api/loadhistories-200- OK-

11-01 09:15 - [INFO] (pharmit.py).send_request(43) - https://api.pharmit.kz/api/loadhistories-200- OK-
2
11-01 09:15 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 09:15 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 09:15 - [INFO] (pharmit.py).send_request(43) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
